### ISSUE TITLE
Preprint or other citation?

### ISSUE THREAD

**Issue by sheinasim-USDA** [lh3/srf#1]
Hello! 

I'm in the process of writing up a paper which uses SRF (in addition to TRF) to identify telomere motifs and their locations in the assembly. Is there a preprint that I can cite in the methods?

Thanks!
Sheina

**Comment by lh3** [comment]
There is not a preprint on SRF. You may cite the github repo for now if you want to do it. Thanks for checking anyway.

**Comment by lh3** [comment]
SRF has a preprint now: https://doi.org/10.48550/arXiv.2304.09729
