### ISSUE TITLE
fish assembly test, 

### ISSUE THREAD

**Issue by yuhuang-genomics** [lh3/srf#10]
Dear Prof. Li,

I'm running SRF with a T2T fish genome assembly (GCA_019455525.1 from article doi.org/10.1186/s13059-021-02430-y) using the provided parameters:
`kmc -fm -k151 -t16 -ci20 -cs100000 GCA_019455525.1.fna count.kmc tmp_dir`
`minimap2 -c -N1000000 -f1000 -r100,100 <(./srfutils.js enlong eel.srf.fa) GCA_019455525.1.fna  >eel.srf-aln.paf`
and other commands with default parameters. 

The generated bed/len shows that SRF circ15-1047 is the most abundant and it is Cen-524 monomer reported in the article, though twice the size of Cen-524. However, it failed to identify centromere in some chromosomes (e.g. Chr1, Chr2,.. ChrY) that were successfully identified in the article.
Here is the reported data (left), and my test with SRF(right): (Y=match, N=not match, ?=different location)
[SRF fish assembly test.txt](https://github.com/lh3/srf/files/11879454/SRF.fish.assembly.test.txt)

Here is the seqs of Cen-524 and SRF circ15-1047:
[monomer seqs.txt](https://github.com/lh3/srf/files/11879672/monomer.seqs.txt)

My questions are:
1. Why SRF failed some chromosomes?
2. Why regions identified by SRF are usually slighly smaller than the reported data?
3. Can SRF be used for assembling of telomere?

**Comment by yuhuang-genomics** [comment]
I wonder if SRF misidentifies the "monomer" cause circ15-1047 looks much like a dimer.

**Comment by lh3** [comment]
See [README](https://github.com/lh3/srf#analysis) and the preprint. SRF often reports a contig like this. You can use TRF or TRF-mod to get the monomer. As to other questions:

1. I don't know. You need to look at the alignment. 
2. See the preprint. The boundary usually varies a lot with alignment parameters and alignment filtering.
3. Usually, yes, but this assembly doesn't look like T2T. The paper only said Y is T2T. I would recommend to run SRF on reads instead.

**Comment by lh3** [comment]
Also, the paper is using peregrine for assembly. Peregrine is unable to get good centromere assembly. I would redo the assembly with hifiasm, hicanu or verrko. I would not trust any repeat analysis based on this assembly.
