### ISSUE TITLE
srf: srf.c:143: ca_kmer_read: Assertion `(i&1) == 1' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by atotickov** [lh3/srf#11]
Hi, Heng. Can you please advise on what might be the issue?
I have set up a separate conda environment, and in this environment, I have installed the following: `k8`, `minimap2`, and `blast`.
The installation of the `srf` and `kmc` programs was done according to the instructions on github pages.

I used kmc to compute 50-mers, and the program completed without any errors. However, I encountered an error when trying to run srf with the following command:

`srf -p prefix count_kmc.txt > srf_contigs.fa`

The error message looks like this:
```
srf: srf.c:143: ca_kmer_read: Assertion `(i&1) == 1' failed.
Aborted (core dumped)
```
I would appreciate your assistance!

**Comment by lh3** [comment]
Please try a k-mer of odd number (like 51bp, not 50bp).
