### ISSUE TITLE
Meaning of srf output

### ISSUE THREAD

**Issue by rapamycin** [lh3/srf#18]
Hi Heng,

Thank you for developing SRF.

For the output of SRF, what's the meaning of the minimum, maximum and average k-mer occurrences on the contig?
>prefix#circ1-2126 min=34936,max=100000,avg=94336
AGACCGTGGGGATGCTGGCGAAGCT...
The first FASTA record tells us the first contig is 2126bp in length. The minimum, maximum and average k-mer occurrences on the contig are 34936, 100000 and 94336, respectively.

Thanks,

**Comment by rapamycin** [comment]
I suppose the meaning of the output be like the following.
If we have a contig with length of L, and kmer size of K, then, the total number of kmers is L-K+1. For the kmers of this contig, they occured in the sequenced reads or assemblies for different times. So the min. max. ave. occurences of these (L-K+1) kmers were reported.
Is that right? But is can't explain the telomere satellite, as the contig length (L=6) is smaller than kmer length(e.g. 51bp kmer).

**Comment by lh3** [comment]
You have described it. SRF contig length is irrelevant.

**Comment by rapamycin** [comment]
Thank you for clarify.
If we know the average occurrences of k-mers in a contig, can we estimate the roughly fraction of the genome that this contig represents, just from the sequenced reads (without using assemblies)?
