### ISSUE TITLE
insufficient memory on a large chromosome

### ISSUE THREAD

**Issue by MichaelHiller** [lh3/srf#2]
Dear Heng, 

I ran SRF on 1500 vertebrates and all is fine, except for the Indian muntjac, which has a 
CM018501	1107743563
1.1 GB chromosome. 

Using the parameters you described in the HOWTO, minimap2 crashes with 
minimap2 -c -N1000000 -f1000 -r100,100 -t32 <(srfutils.js enlong srf.fa) HLmunMun1.fa > srf-aln.paf
[M::mm_idx_gen::0.009*0.50] collected minimizers
[M::mm_idx_gen::0.010*0.92] sorted minimizers
[M::main::0.010*0.92] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.010*0.92] mid_occ = 1000
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.010*0.92] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
[morecore] insufficient memory

Our server has 1 TB RAM and 544 GB are free. 
Googling in the minimap2 github, I tried
- reducing cores to -t8 or -t1
- increasing -K to up to -K32000M 
- --cap-sw-mem=4g
but all insufficient mem. 

With --no-kalloc , I get a segfault
minimap2 -c -N1000000 -f1000 -r100,100 -t1 --no-kalloc <(srfutils.js enlong srf.fa) HLmunMun1.fa > srf-aln.paf
[M::mm_idx_gen::0.009*0.46] collected minimizers
[M::mm_idx_gen::0.009*0.48] sorted minimizers
[M::main::0.009*0.48] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.009*0.48] mid_occ = 1000
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.009*0.48] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
Segmentation fault (core dumped)

Any idea on which minimap2 parameters I should use? 
I suspect the problem is the big chrom. 

Thx a lot

**Comment by lh3** [comment]
> `[M::main::0.010*0.92] loaded/built the index for 0 target sequence(s)`

This is because there are no sequences in `srf.fa`. It seems that minimap2 can't handle empty reference. Still a bug.

**Comment by MichaelHiller** [comment]
I see. There are 7762 high-occurrence kmers in count.txt, but srf -p prefix 
  srf -p prefix count.txt > srf.fa
  [M::main] read 7762 distinct k-mers
does not identify any satellite DNA. 
Meaning, I can stop and no need to run minimap2. 

I overlooked that. 
Thx.
