### ISSUE TITLE
Satellite Repeats in genome assemblies

### ISSUE THREAD

**Issue by sanyalab** [lh3/srf#4]
Hello,

I have High-quality genome assemblies in a weed species. Can this tool be used to identify HOR's and other satellite repeats in whole genome assemblies?

Thanks

**Comment by lh3** [comment]
SRF works with assemblies, provided that it is a HiFi or duplex assembly assembled by hifiasm, verkko, HiCanu or LJA. Most other assemblers will collapse satellites.
