### ISSUE TITLE
Annotate ultra-long reads with SRF

### ISSUE THREAD

**Issue by baozg** [lh3/srf#5]
Hi, @lh3 

Could we use SRF to annotate ultra-long reads with HiFi/Duplex-derived repeat?

**Comment by lh3** [comment]
Yes, you can, but the estimate may be less accurate.

**Comment by baozg** [comment]
Sorry for the implicit question. Do you have any suggestions for mapping parameters of ultra-long reads? Was still `-c -N1000000 -f1000 -r100,100`. It should be similar with https://github.com/makovalab-psu/NoiseCancellingRepeatFinder
