### ISSUE TITLE
srf crash

### ISSUE THREAD

**Issue by MichaelHiller** [lh3/srf#7]
Dear Heng, 

we have run srf on a bunch of genomes, which always worked fine, but here I found a crash.

kmc -fm -k151 -t8 -ci100 -cs100000 assembly.fa count.kmc tmp_dir/
kmc_dump count.kmc count.txt

srf -p prefix count.txt > srf.fa
[M::main] read 35958 distinct k-mers
malloc(): invalid next size (unsorted)
Aborted (core dumped)
 
I attach the count.txt (gzipped).

Thanks for having a look.
-Michael
[count.txt.gz](https://github.com/lh3/srf/files/11323708/count.txt.gz)

**Comment by lh3** [comment]
Thanks a lot for the example. It is a bug. Now fixed on the github HEAD.

**Comment by MichaelHiller** [comment]
Thanks for the superquick response. I should have checked whether we have the latest code version. Sorry.

**Comment by lh3** [comment]
Oh, it is entirely my fault. I just fixed the bug using your example like 5 minutes ago.
